### ISSUE TITLE
 MYRTUS.zip is not recognized as a project

### ISSUE THREAD

**Issue by alebagnato** [Modelio-R-D/MYRTUS#1]
Dear Modelio Team, I am trying to install the Myrtus Project Template https://github.com/Modelio-R-D/MYRTUS
I have proceeded following the guidelines but unfortunatelly the zipped project is not recognized in my Modelio
Step 1: Install Modelio 5.4.1

    Visit the Modelio releases page on GitHub by clicking here and download the appropriate installer for your operating system: https://github.com/ModelioOpenSource/Modelio/releases/tag/v5.4.1.

Step 2: Clone the Myrthus template Project and make it a zip file, 
git clone https://github.com/Modelio-R-D/MYRTUS.git + zipped the whole archive

Step 3: Import the Project into Modelio : fails and my MYRTUS.zip is not recognized as a project
 
![image](https://github.com/Modelio-R-D/MYRTUS/assets/9965053/f3811d53-1884-4a1e-9056-f06e4819ddb7)

Many thanks for your help!
Alessandra

**Comment by Amina-Moussaoui** [comment]
You should first clone the project and then only zip the "Myrthus template Project"  and not the whole repository. 
The project should then be imported correctly .

**Comment by alebagnato** [comment]
Thanks!


Sent from Yahoo Mail for iPhone


On Thursday, February 8, 2024, 2:19 PM, Amina-Moussaoui ***@***.***> wrote:




You should first clone the project and then only zip the "Myrthus template Project" and not the whole repository.
The project should then be imported correctly .
